# -*- coding: utf-8 -*-
"""api_combined.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GYG_TWywIxjzcXg1JLwlPbNVete7K4ef
"""

from fastapi import FastAPI, UploadFile, File
from fastapi.responses import JSONResponse
from ultralytics import YOLO
from PIL import Image
import torch
import numpy as np
import cv2
import albumentations as A
from albumentations.pytorch import ToTensorV2
import segmentation_models_pytorch as smp
import io, time, traceback

# =========================================================
# FastAPI 초기화
# =========================================================
app = FastAPI(title="YOLO + DeepLabV3+ Unified API")

# =========================================================
# YOLO (객체 탐지) 모델 로드
# =========================================================
YOLO_MODEL_PATH = "best2.pt"
yolo_model = YOLO(YOLO_MODEL_PATH)  # ← 반드시 이렇게 해야 함
yolo_model.fuse()  # 추론 속도 개선

is_busy = False

@app.get("/status")
def status():
    return {"status": "busy" if is_busy else "idle"}

# =========================================================
# DeepLabV3+ 모델 로드
# =========================================================
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DLAB_MODEL_PATH = "best_dlab30.pth"

def load_dlab_model():
    model = smp.DeepLabV3Plus(
        encoder_name="resnet34",
        encoder_weights="imagenet",
        in_channels=3,
        classes=1
    )
    model.load_state_dict(torch.load(DLAB_MODEL_PATH, map_location=DEVICE))
    model.to(DEVICE)
    model.eval()
    return model

dlab_model = load_dlab_model()
print("✅ DeepLabV3+ model loaded successfully")

# ---------------------------------------------------------
# 전처리 파이프라인
# ---------------------------------------------------------
val_tf = A.Compose([
    A.Resize(512, 512),
    A.Normalize(mean=(0.485, 0.456, 0.406),
                std=(0.229, 0.224, 0.225)),
    ToTensorV2(),
])

def preprocess(image):
    aug = val_tf(image=image)
    return aug["image"].unsqueeze(0).to(DEVICE)

def predict_mask(image_tensor):
    with torch.no_grad():
        pred = dlab_model(image_tensor)
        pred_mask = torch.sigmoid(pred).squeeze().cpu().numpy()
        return (pred_mask > 0.38).astype(np.uint8)


def calculate_area(pred_mask, orig_shape):
    orig_h, orig_w = orig_shape
    pred_mask_resized = cv2.resize(pred_mask, (orig_w, orig_h), interpolation=cv2.INTER_NEAREST)
    area_pixels = np.sum(pred_mask_resized)
    total_pixels = orig_h * orig_w
    area_ratio = (area_pixels / total_pixels) * 100
    pixel_area_cm2 = 0.0001  # 1픽셀 = 0.01cm² 가정
    area_cm2 = area_pixels * pixel_area_cm2
    return area_pixels, area_ratio, area_cm2

# =========================================================
# YOLO /detect endpoint
# =========================================================
@app.post("/detect")
async def detect_objects(file: UploadFile = File(...)):
    global is_busy
    try:
        is_busy = True

        image_bytes = await file.read()
        image = Image.open(io.BytesIO(image_bytes)).convert("RGB")

        start_time = time.time()
        results = yolo_model(image)  # ← Ultralytics YOLO inference
        inference_time = round((time.time() - start_time) * 1000, 2)

        predictions = []
        object_count = 0

        # results[0].boxes 사용
        for box in results[0].boxes:
            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            x1, y1, x2, y2 = box.xyxy[0].tolist()

            if conf >= 0.3:
                object_count += 1
                predictions.append({
                    "class_id": cls_id,
                    "confidence": round(conf * 100, 2),
                    "box": [round(x1, 2), round(y1, 2), round(x2, 2), round(y2, 2)]
                })

        return JSONResponse(content={
            "model": "YOLO",
            "filename": file.filename,
            "object_count": object_count,
            "inference_time_ms": inference_time,
            "predictions": predictions
        })

    except Exception as e:
        traceback.print_exc()
        return JSONResponse(status_code=500, content={"error": str(e)})

    finally:
        is_busy = False

# =========================================================
# DeepLab /segment endpoint
# =========================================================
@app.post("/segment")
async def segment_area(file: UploadFile = File(...)):
    try:
        start_time = time.time()

        contents = await file.read()
        npimg = np.frombuffer(contents, np.uint8)
        image = cv2.imdecode(npimg, cv2.IMREAD_COLOR)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        orig_shape = image.shape[:2]

        image_t = preprocess(image)
        pred_mask = predict_mask(image_t)

        area_pixels, area_ratio, area_cm2 = calculate_area(pred_mask, orig_shape)
        inference_time_ms = round((time.time() - start_time) * 1000, 2)

        return JSONResponse(content={
            "model": "DeepLabV3+",
            "filename": file.filename,
            "area_count": int(area_pixels),
            "area_ratio_percent": round(area_ratio, 2),
            "area_cm2_assumed": round(area_cm2, 2),
            "inference_time_ms": inference_time_ms
        })

    except Exception as e:
        traceback.print_exc()
        return JSONResponse(status_code=500, content={"error": str(e)})